### ISSUE TITLE
Subpixel cluster jobs failing near end of job queues

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#378]
Within the last 173 of 11521 slurm jobs for the subpixel register, 12 are failing with the following message:

 ```
Traceback (most recent call last):
  File "/home/ladoramkershner/miniconda3/envs/autocnet_local/bin/acn_subpixel", line 7, in <module>
     exec(compile(f.read(), __file__, 'exec'))
   File "/work/users/ladoramkershner/projects/autocnet/bin/acn_subpixel", line 49, in <module>
     conf['working_queue'])
   File "/work/users/ladoramkershner/projects/autocnet/autocnet/io/db/redis_queue.py", line 31, in pop_computetime_push
     msg = json.loads(queue.rpop(inqueue), object_hook=object_hook)
   File "/home/ladoramkershner/miniconda3/envs/autocnet_local/lib/python3.7/json/__init__.py", line 341, in loads
     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
 TypeError: the JSON object must be str, bytes ordf bytearray, not NoneType
```

Additionally, cluster_subpixel_register should submit one job per point however there are an extra 12 slurm logs than I have points in my database.

I am working in an environment where autocnet's last merge is #375 and plio and plurmy are both develop installed (as opposed to fetching from conda).  I don't think this is actually an issue with subpixel register running, but just an error resulting from autocnet trying to pull from an empty queue.

**Comment by jlaura** [comment]
That is the message that you see when no message is on the queue. We should alter this to:

```python
msg = queue.rpop(inqueue)
if msg is None:
    warnings.warn('Expected to process a cluster job, but the message queue is empty.')
    sys.exit()
msg = json.loads(msg, object_hook=object_hook)
```

Do you want to update the bin scripts?

**Comment by ladoramkershner** [comment]
Can do, buckaroo.

**Comment by ladoramkershner** [comment]
Just opened a pull request (#379) to fix this! No tests were written though, does that seem like a necessity?

**Comment by ladoramkershner** [comment]
Our PR did not work how we expected it to, when the queue runs out, instead of returning None for the msg it seems to pick up left over messages from the distribution points cluster job. I am not sure if that is possible, but I get the following error from the file autocnet.**subpixel_register**-3249452.3243294_750.out

```
{'id': 544, 'distribute_points_kwargs': {}, 'walltime': '00:10:00', 'cam_type': 'csm', 'max_time': 1564173738.0679371}
Subpixel registering point 544
Traceback (most recent call last):
  File "/home/ladoramkershner/miniconda3/envs/autocnet_local/bin/acn_subpixel", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/work/users/ladoramkershner/projects/autocnet/bin/acn_subpixel", line 56, in <module>
    main(msg, config)
  File "/work/users/ladoramkershner/projects/autocnet/bin/acn_subpixel", line 39, in main
    iterative_phase_kwargs=msg['iterative_phase_kwargs'],
KeyError: 'iterative_phase_kwargs'
```

**Comment by ladoramkershner** [comment]
The messages for subpixel_register should look something more like 

```
{'id': 262, 'iterative_phase_kwargs': {'size': 71}, 'subpixel_template_kwargs': {'image_size': [121, 121]}, 'threshold': 0.005, 'walltime': '00:10:00', 'max_time': 1564173728.5565495}
```
